### ISSUE TITLE
WPWebDriver throws "Could not login as admin, password] after 5 attempts." When running `tric run acceptance`

### ISSUE THREAD

**Issue by borkweb** [moderntribe/products-test-automation#43]
![Screen Shot 2020-04-17 at 3 27 54 PM](https://user-images.githubusercontent.com/430385/79606721-0be73780-80c0-11ea-90f5-8c80509ab218.png)

This is against `event-tickets`.

**Comment by lucatume** [comment]
Same issue as #43, fixed.
